### Register
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "fullName": "Admin 0ne",
  "username": "admin_1",
  "email": "admin@mail.com",
  "password": "1234",
  "role": "admin"
  
}

### Login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "1234"
}

### Me (cookie must be sent by client; Postman: enable cookie jar)
GET http://localhost:5000/api/users/me

### Logout
POST http://localhost:5000/api/users/logout