export const BOARD_LANES = [
  "BOOKED",
  "INTAKE",
  "BAGGED",
  "LOADED",
  "IN_TRANSIT",
  "ARRIVED_HUB",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
];

// UI → API status map
export const LANE_TO_STATUS = {
  INTAKE: "PICKED_UP",
  BAGGED: "IN_TRANSIT",
  LOADED: "IN_TRANSIT",
  IN_TRANSIT: "IN_TRANSIT",
  ARRIVED_HUB: "AT_HUB",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
};
